<?php

/**
 * Implements hook_required_fedora_objects().
 */
function islandora_authority_sp_required_fedora_objects() {
  $module_path = drupal_get_path('module','islandora_authority_sp');
	$objects = array(
	  'islandora_authority_sp' => array(
	    'module' => 'islandora_authority_sp',
      'title' => 'Islandora Authority Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:authorityCModel',
          'dsid' => 'ISLANDORACM',
          'label' => 'Islandora Authority Content Model',
          'cmodel' => 'fedora-system:ContentModel-3.0',
          'datastream_file' => "$module_path/xml/AUTHORITY_SP_CMODEL.xml",
        ),
        array(
          'pid' => 'islandora:authorityCollection',
          'label' => 'Islandora Authority Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/person.gif",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/AUTHORITY_COLLECTIONPOLICY.xml",
            ),
          ),
        ),
      ),
	  ),
	);
  return $objects;
}